language: node_js
addons:
  sauce_connect: true
env:
  global:
  - secure: pPp8AifCrMkuBbyfmA14Nn0BsZSyO0HZdsIoFJJk8FWn1Y/kOhBELleCa7dejeXVSUAoVjyipIG4oolZL3O4OQyynNU2iMYSET3dYKg/OkwnV+40XUNz8nyfnTvnSW2bkEYuUG/VYOqnzmBqsK8xtGx9MwFjEVpMyMlUhSLqXQqfqgtokaBV690gH92BJ2jIcvkpKzCBz6i9NQEP/sJHixdIW/T52GaqIL+20k4qagtkwf1EwP7l6E8Q+UJUr7qVDky0gSUpWuFCd2W3ZmUr+gog1J20fLL5pDXhsRlE3ZjT94/6cEY5/pMmQc1mzNrLhzmg+KS15idzTjNxfQotxynegf42rCTOb7i9aigBF0rHpjrqNLiJhCvENg+i3lt0sZzCs8uQo+GrNNxI+Qg0sJzWEmtD3WAltqKlly6rC2O4ySbf/0Usgo/EvlDpL2wffRZp3aUczl6lejZWm5lQI7cfDukB20/Nopbv6AUFApv1PJ9RcTshnCbMcY3x9NIr6sucZlLz+bSOXvSQ3j8vLW5zu0bKGfpjs5R5apaHVgysSI7gm09f4UT9sFBLwTTZ1NODLwi8xKm8MnIJQvTBujAMa8y/jJEkitCN8tTK4iBwIrK+bYwxeuQpUPlK2toFQL8SxQMZZHfIxEXzPSkuVsGls0eiJAJqc56ndryaUiQ=
  - secure: Db3WH298vglzgG0Veauz9A7zj86swBI/Q+4xURNPRv7w0g3HidfsO2h7Js6vg/Ffb9PLnTX8Uzf5+weuMnDSydr1354TqlYUSKBHEngFDhOvIZ1qC1NESPXtVVCmK0kjHVgPBoeYDXFQE78jdz3KtqlRWfiVhAaWKqtW03q/GusdbOqp2fkqAH+t+bum1lji3Nkv+jFVy3rD5ePpKH7U/tUgGhCS6ROB0DmxGehOA97k3/RURJ54ivF8Lybt/0daI7kPJ5mvcxKFwcDnR3pT2cHaQqmUy3oW1yOiI0JxLyoyqkhJwpOhN+6rRv+19DSAt9osQhSQUW2CM3B9ubOC++uEHFGU20FwTN75m86tS/0mN4kxXSnwRAsF3frON+Jv+Ubm/cttwUU/nedsUuFUK5i2n98P5StUSEplPfLG4saxsNKFtkWRbQZ3w0CWZcysikDpZgOsIcms/nB0mScEL3DFwDC8i1ZhdsCNHsg2is/eB4TyiD4cupQfGvbR5welf8RnZxVYbYTTuIMgOdRjBGFoRoXzNe/qrGVNiRoTEKNv1+4F2iNgxbjT0TQKPaLIHZ/alEuaA6gViPbD5KFYg4bgHzHDve1ahxm5U1sJQMGHo2IJOLEIrN4jkqb7ZApLPMFXnJeppIP4EY1i5eysYhWxi6TbmClCvW3tLfdHDmo=
before_script:
- python -m SimpleHTTPServer &
- sleep 2
node_js:
- '5.0.0'

